### ISSUE TITLE
Suggest to instruct user to "get cluster credentials"

### ISSUE THREAD

**Issue by mph13** [CrowdStrike/Cloud-GCP#17]
Suggest edit here:
https://github.com/CrowdStrike/Cloud-GCP/blob/main/container/gke-implementation-guide.md

[Step 2 Create GKE Cluster](https://github.com/CrowdStrike/Cloud-GCP/blob/main/container/gke-implementation-guide.md#step-2-create-gke-cluster)
Suggested addition:
Once the cluster is created, before accessing the cluster, run the command `gcloud container clusters get-credentials <cluster name>`, which will update the kubeconfig file with credentials and endpoint information to point kubectl to the newly created cluster.

**Comment by isimluk** [comment]
:+1: 

Would you mind submitting PR for this? It is as easy to hit the pencil button at of the document.

**Comment by mph13** [comment]
I don't mind at all! Thought I'd start with an issue and see how it went ;)
https://github.com/CrowdStrike/Cloud-GCP/compare/main...MPH13:patch-1
