### ISSUE TITLE
Outdated documentation | Issues with reading from GCR

### ISSUE THREAD

**Issue by stascnb** [CrowdStrike/Cloud-GCP#34]
Hey, we just were trying to follow the documentation for GCP specifically and there are a few issues was hoping you could help us with.

1. The provided image to build and push docker sensor to our own registry is lacking some plugins - https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke , had to install it on the top of the image

2. Running `falcon-container-sensor-push $FALCON_IMAGE_URI` results in this error:
```
WARNING: FALCON_CLOUD environment variable missing. Assuming FALCON_CLOUD=us-1
Login Succeeded!
FATA[0004] Error listing repository tags: fetching tags list: invalid status code from registry 404 (Not Found)
```

It states that it cannot fetch tags or list from our GCR, however. When i run `gcloud container images list-tags gcr.io/central-gcr/sample/1` it lists the following:

```
DIGEST        TAGS    TIMESTAMP
897e1eb22e47  latest  2023-09-15T00:16:31
8499253f9679          2023-09-15T00:04:16
```
I've doubled check and I can view, I can pull, and I can push to that registry with no problem.

I've tried searching where the command `falcon-container-sensor-push` lives, to see maybe there is something with image it tries to search on Falcon side, or assigning a wrong IMAGE_URI but no luck.

Would appreciate help on this

**Comment by redhatrises** [comment]
Closing this issue as we no longer support these tools from this repo. Either Skopeo should be used directly or the container script from github.com/crowdstrike/falcon-scripts should be used.
